/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_UserManager */

#ifndef _Included_com_example_UserManager
#define _Included_com_example_UserManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_UserManager
 * Method:    createLocalUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_UserManager_createLocalUser
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
